steps:
  - name: gcr.io/cloud-builders/docker@sha256:dafc4da4ca161f621d10b8c2a78bc3fe8935f72857a3cbc2c010e9bc693b67d9
    args:
      - pull

  - name: gcr.io/cloud-builders/docker@sha256:dafc4da4ca161f621d10b8c2a78bc3fe8935f72857a3cbc2c010e9bc693b67d9
    args:
      - build

  - id: test
    name: gcr.io/my-project/test

  - id: fetch
    name: gcr.io/cloud-builders/gsutil@sha256:d5b9b37cbae9b0e3efa13bc5b2000e289ac08346b629ccdeffcafc0ee043223d
    waitFor:
      - '-'

  - name: gcr.io/my-project/package
    waitFor:
      - fetch
      - test

  - name: gcr.io/ma-project/deploy
