steps:
  - name: gcr.io/cloud-builders/docker@sha256:232285ef9e080bfae5d6e5782269768374fd3f4782c4bcadcaa1f359b86d0737
    args:
      - pull

  - name: gcr.io/cloud-builders/docker@sha256:232285ef9e080bfae5d6e5782269768374fd3f4782c4bcadcaa1f359b86d0737
    args:
      - build

  - id: test
    name: gcr.io/my-project/test

  - id: fetch
    name: gcr.io/cloud-builders/gsutil@sha256:0909889d769428974e8954f2c8d1416162d9e8d29c268df63051241d84226970
    waitFor:
      - '-'

  - name: gcr.io/my-project/package
    waitFor:
      - fetch
      - test

  - name: gcr.io/ma-project/deploy
