steps:
  - name: gcr.io/cloud-builders/docker@sha256:5a298601d0ce155813f6fce648dc3d3fd6fe6d5ff5cef43427f0a5404f64d4c6
    args:
      - pull

  - name: gcr.io/cloud-builders/docker@sha256:5a298601d0ce155813f6fce648dc3d3fd6fe6d5ff5cef43427f0a5404f64d4c6
    args:
      - build

  - id: test
    name: gcr.io/my-project/test

  - id: fetch
    name: gcr.io/cloud-builders/gsutil@sha256:bc68b53e7adfea6ac96f3cbca355da58e43006c575e12941590ed1e87fa6c30c
    waitFor:
      - '-'

  - name: gcr.io/my-project/package
    waitFor:
      - fetch
      - test

  - name: gcr.io/ma-project/deploy
