steps:
  - name: gcr.io/cloud-builders/docker@sha256:b1f24c6cc81385bbf1f3d159bae96150f49fa4dca1f3f14df4411528060b33b5
    args:
      - pull

  - name: gcr.io/cloud-builders/docker@sha256:b1f24c6cc81385bbf1f3d159bae96150f49fa4dca1f3f14df4411528060b33b5
    args:
      - build

  - id: test
    name: gcr.io/my-project/test

  - id: fetch
    name: gcr.io/cloud-builders/gsutil@sha256:5c541a143ef0cee924ad2efd032449ec4d745010d982ef9ed650d56aac97fc0e
    waitFor:
      - '-'

  - name: gcr.io/my-project/package
    waitFor:
      - fetch
      - test

  - name: gcr.io/ma-project/deploy
