steps:
  - name: gcr.io/cloud-builders/docker@sha256:78dea261a2243e5b41a4c4275b110a53154a81f87af618c39bb15e8059b199fc
    args:
      - pull

  - name: gcr.io/cloud-builders/docker@sha256:78dea261a2243e5b41a4c4275b110a53154a81f87af618c39bb15e8059b199fc
    args:
      - build

  - id: test
    name: gcr.io/my-project/test

  - id: fetch
    name: gcr.io/cloud-builders/gsutil@sha256:5d3731a7440b78c7aff3ae13c498d8706ba6859581229b92d2f78f33df17ca3d
    waitFor:
      - '-'

  - name: gcr.io/my-project/package
    waitFor:
      - fetch
      - test

  - name: gcr.io/ma-project/deploy
