steps:
  - name: gcr.io/cloud-builders/docker@sha256:1a1eb8b25d3af1844351f055ac092237987d09c59098a54f5db9f01a6e480b39
    args:
      - pull

  - name: gcr.io/cloud-builders/docker@sha256:1a1eb8b25d3af1844351f055ac092237987d09c59098a54f5db9f01a6e480b39
    args:
      - build

  - id: test
    name: gcr.io/my-project/test

  - id: fetch
    name: gcr.io/cloud-builders/gsutil@sha256:d5b9b37cbae9b0e3efa13bc5b2000e289ac08346b629ccdeffcafc0ee043223d
    waitFor:
      - '-'

  - name: gcr.io/my-project/package
    waitFor:
      - fetch
      - test

  - name: gcr.io/ma-project/deploy
