builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - binaries:
      - cloudbuildgraph
    image_templates:
      - 'ghcr.io/patrickhoefler/cloudbuildgraph:latest'
      - 'ghcr.io/patrickhoefler/cloudbuildgraph:{{ .Major }}'
      - 'ghcr.io/patrickhoefler/cloudbuildgraph:{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/patrickhoefler/cloudbuildgraph:{{ .Major }}.{{ .Minor }}.{{ .Patch }}'

brews:
  - tap:
      owner: patrickhoefler
      name: homebrew-cloudbuildgraph

    homepage: https://github.com/patrickhoefler/cloudbuildgraph
    description: 'Visualize your Google Cloud Build pipeline'

    dependencies:
      - graphviz
